### ISSUE TITLE
parseFromTokenizer hangs (forever, rather than throwing) on duration error

### ISSUE THREAD

**Issue by charles-rc** [Borewit/tokenizer-s3#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

7.14.0

### JavaScript module eco system

CommonJS modules (CJS), music-medata ≤ version 7

### Current Behavior

Hey! 

Thanks for the library. It's awesome!

We noticed a bug recently where certain corrupt files cause `parseFromTokenizer` to infinitely hang. We're storing files in S3, creating a tokenizer and then running `parseFromTokenizer`. See the code below for an example:

```js
  const s3Tokenizer = await makeTokenizer(s3Client, {
    Bucket: bucket,
    Key: key,
  });
  const metadata = await parseFromTokenizer(s3Client, { duration: true });
```

For files with corrupt duration, the above code does not throw or return a response. It just seems to hang indefinitely.

See this file for an example - [corrupt_duration.mp3.zip](https://github.com/Borewit/music-metadata/files/15403791/corrupt_duration.mp3.zip)

When loaded into Foobar2000 and then running the Verifier the file reports an error of "Failed: Reported length is inaccurate: 1:57 vs :1:33 decoded".

### Expected Behavior

The library throws an error or returns an error response.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Hi @charles-rc , I have not tried parsing this file from the S3 cloud, but I did directly on a file:

```js
  // https://github.com/Borewit/music-metadata/issues/2052
  it('should parse corrupt_duration.mp3', async () => {
    const filePath = path.join(mp3SamplePath, 'corrupt_duration.mp3');

    const {format} = await mm.parseFile(filePath, {duration: true});

    assert.strictEqual(format.container, 'MPEG');
    assert.strictEqual(format.codec, 'MPEG 2.5 Layer 3');
    assert.strictEqual(format.duration, 5625.288);
  });
```
which works, but it takes a while. The entire MP3 file is parsed, in very small chunks. That most likely exhausting the S3 connection. The mechanism is not perfect, the idea is to download chunks lazy. By setting the duration flag, you essentially enable this very expensive algorithm, in combination with this S3, it becomes just to expensive.

**Comment by charles-rc** [comment]
Hey @Borewit, thanks for your reply! I just saw this.

What would you recommend instead? We want to upload audio files into S3 and record the duration in our database. Is there a better way of working out the duration?

**Comment by Borewit** [comment]
Ensure the duration is set as part of the metadata. Any proper encoder will do that.

You can use special S3 access in combination with `music-metadata` for partial access: https://github.com/Borewit/tokenizer-s3

See examples here:

https://github.com/Borewit/tokenizer-s3/blob/master/test/test.ts#L82-L108

**Comment by charles-rc** [comment]
That sounds like what we already do. I guess I didn't realise that setting `duration: true` means it'll parse the duration from the entire file rather than the metadata.

I guess we should remove the duration flag and just rely on the mp3 files being properly encoded? That should stop the hanging and we can return a proper error message if metadata is missing the duration.

Thanks a lot for your libraries. They are very helpful!

**Comment by charles-rc** [comment]
Awesome! Thanks a lot for your help!
