### ISSUE TITLE
Loose strict version coupling with aws-sdk

### ISSUE THREAD

**Issue by Borewit** [Borewit/tokenizer-s3#63]
Maybe a peer dependency relation with [aws-sdk-js](https://github.com/aws/aws-sdk-js) is better, to give the dependent modules more control over that version.

**Comment by vecerek** [comment]
Is there a plan to support [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3)?

**Comment by Borewit** [comment]
> Is there a plan to support [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3)?

See https://github.com/Borewit/tokenizer-s3/pull/153#issuecomment-708933648
