### ISSUE TITLE
Readme on npm is out of date

### ISSUE THREAD

**Issue by mattboutet** [Borewit/tokenizer-s3#670]
For v0.2.0 the readme file on npm is out of date:

From npm:

```
const FileType = require('file-type');
const S3 = require('aws-sdk/clients/s3');
```

from the readme in this repo:
```
const FileType = require('file-type');
const { S3Client } = require('@aws-sdk/client-s3');
```

The latter works, the former does not:
```
TypeError: this.s3.send is not a function

    at S3Request.getRangedRequest (/app/node_modules/@tokenizer/s3/lib/s3-request.js:68:24)
```

A quick look around shows that 0.2.0 is at https://github.com/Borewit/tokenizer-s3/tree/aed9a18c5a1ade1ef3bb67fa4903493808836fc2 and the updates to the readme happened later.  Seems possible it'll just take a patch version bump and a new publish to get things squared away.

**Comment by Borewit** [comment]
Solved: [v0.2.1](https://github.com/Borewit/tokenizer-s3/releases/tag/v0.2.1)
